### PR TITLE
Allow a custom UCD path to be supplied.

### PR DESCRIPTION
**Pull request by ezzatron**
Summary of changes:
- Adds support for using external UCD data.
- Export a function instead of the codepoints array. This function takes an optional path to the UCD data.
- Moved `DerivedNumericValues.txt` to match its default path in the UCD.
- Updated documentation to match code changes.
- Also documented the use of `undefined` for unassigned codepoints.
- Added a simple test script to verify everything is still working.

I was just playing around trying to implement the PRECIS framework over at [ezzatron/precis-js](https://github.com/ezzatron/precis-js), and found your awesome Unicode repos. For my purposes, I wanted to use my own UCD data, and these changes let me do so. Hope you find them useful!

### CODE REVIEW

**Comment by devongovett** [comment]
I like this, but one problem with doing it like this is that it reparses the files every time you call the function, vs running just the first time the module is required. What about leaving it like this, but rename `index.coffee` to `parser.coffee`, and make a new `index.coffee` that just has `module.exports = require('./parser')()` in it. That would allow the module to work exactly as it does now, but if you needed to use a different UCD, you could `require('codepoints/parser')(...)`. What do you think?

**Comment by ezzatron** [comment]
Yeah, that sounds good. I'll make those changes ASAP.

**Comment by ezzatron** [comment]
All done. Only thing I couldn't really check was the NPM `prepublish` script changes.

**Comment by devongovett** [comment]
Published to npm in v1.1.0. Thanks!

**Comment by ezzatron** [comment]
Nice :+1:

**Pull request merged**
